### PR TITLE
passed all tests in test_TableDatabase

### PR DESCRIPTION
**Pull request by liuluheng**
this PR separate the tdb thread and main, add snapshot for all collections, reorganize files into npl modules folders,and passed all tests in test_TableDatabase. **But the performance (see test_TableDatabase) is heavily reduced due to the raft algorithm**

### CODE REVIEW

**Comment by LiXizhi** [comment]
where is the test result? 
I think I am more concerned with throughput, instead of round trip time. it should not decrease much in term of throughput.

**Comment by LiXizhi** [comment]
Please resolve the conflict file before I merge and test

**Comment by LiXizhi** [comment]
Anyway, cool news~

```
TableDB 分布式数据库基本测试通过了。
https://github.com/NPLPackages/TableDB/pull/5
需要计划一个项目在实际的非关键性系统中测试和使用。 @曹永锋 @逍遥--吴香安  可以作为这次summer of code 实习生的一个课题。 
比如开发一个network event/log system 日志与用户行为分析系统。  
@实习李志强 

```

**Comment by liuluheng** [comment]
I used git rebase to resovle the conflict... test code is in `npl_mod/TableDBApp/App.lua`, u can test the `TestInsertThroughputNoIndex(RaftSqliteStore)` to get the result. **There will have many `timout` if u doesnot comment out the `echo({err, data});` in `TestInsertThroughputNoIndex(RaftSqliteStore)`** 

@LiXizhi

**Comment by liuluheng** [comment]
actually the **throughput** is not good, because the call back is called when the entry is **commited**, and if we move the `p:Next()`;  out of callback, it will be much better, but we will get `NPL dispatcher error because NPL_QueueIsFull `...
@LiXizhi

**Comment by LiXizhi** [comment]
I will take a look. I think the throughput may be limited by the way the test case is written.

**Comment by liuluheng** [comment]
Is there any ideas at how to optimise on this?
@LiXizhi

**Pull request merged**
